bgs_raw = [
    ("Gloomhaven", 2017, """Vanquish monsters with strategic cardplay. Fulfill your quest to leave your legacy!""", 8.558),
    ("Pandemic Legacy: Season 1", 2015, """Mutating diseases are spreading around the world - can your team save humanity?""", 8.466),
    ("Brass: Birmingham", 2018, """Build networks, grow industries, and navigate the world of the Industrial Revolution.""", 8.357),
    ("Terraforming Mars", 2016, """Compete with rival CEOs to make Mars habitable and build your corporate empire.""", 8.285),
    ("Twilight Imperium: Fourth Edition", 2017, """Build an intergalactic empire through trade, research, conquest and grand politics.""", 8.241),
    ("Through the Ages: A New Story of Civilization", 2015, """Rewrite history as you build up your civilization in this epic card drafting game!""", 8.193),
    ("Gaia Project", 2017, """Expand, research, upgrade, and settle the galaxy with one of 14 factions.""", 8.168),
    ("Star Wars: Rebellion", 2016, """Strike from your hidden base as the Rebels—or find and destroy it as the Empire.""", 8.163),
    ("Twilight Struggle", 2005, """Relive the Cold War and rewrite history in an epic clash between the USA and USSR.""", 8.137),
    ("Great Western Trail", 2016, """Use strategic outposts and navigate danger as you herd your cattle to Kansas City.""", 8.115),
    ("War of the Ring: Second Edition", 2012, """The Fellowship and the Free Peoples clash with Sauron over the fate of Middle-Earth.""", 8.094),
    ("Spirit Island", 2017, """Island Spirits join forces using elemental powers to defend their home from invaders.""", 8.086),
    ("Scythe", 2016, """Five factions vie for dominance in a war-torn, mech-filled, steampunk 1920s Europe.""", 8.085),
    ("Gloomhaven: Jaws of the Lion", 2020, """Vanquish monsters with strategic cardplay in a 25-scenario Gloomhaven campaign.""", 8.065),
    ("The Castles of Burgundy", 2011, """Plan, trade, and build your Burgundian estate to prosperity and prominence.""", 8.012),
    ("Terra Mystica", 2012, """Play fantastical factions. Expand your influence by terraforming and joining cults.""", 7.993),
    ("7 Wonders Duel", 2015, """Science? Military? What will you draft to win this head-to-head version of 7 Wonders?""", 7.978),
    ("Concordia", 2013, """Lead your Roman dynasty and build the greatest trading empire in the Mediterranean.""", 7.962),
    ("Brass: Lancashire", 2007, """Test your economic mettle as you build and network in the industrial revolution.""", 7.958),
    ("Wingspan", 2019, """Attract a beautiful and diverse collection of birds to your wildlife reserve.""", 7.933),
    ("Arkham Horror: The Card Game", 2016, """Investigate the horrors of Arkham while courting cosmic doom.""", 7.930),
    ("A Feast for Odin", 2016, """Puzzle together the day-to-day life of a Viking village with exploration and raids.""", 7.924),
    ("Viticulture Essential Edition", 2015, """Create the most prosperous winery in Italy from the Tuscan vineyard you've inherited.""", 7.910),
    ("Orléans", 2014, """Craftsmen, scholars & monks can help you reign supreme—but who will turn up to help?""", 7.888),
    ("Mage Knight Board Game", 2011, """Build your hero’s spells, abilities, and artifacts as you explore & conquer cities.""", 7.885),
    ("Nemesis", 2018, """Survive an alien-infested spaceship but beware of other players and their agendas.""", 7.884),
    ("Puerto Rico", 2002, """Ship goods, construct buildings, and choose roles that benefit you more than others.""", 7.869),
    ("Root", 2018, """Decide the fate of the forest as woodland factions fight for contrasting goals.""", 7.854),
    ("Caverna: The Cave Farmers", 2013, """From a simple cave, expand your dwarven home through mining, agriculture, and more.""", 7.852),
    ("Food Chain Magnate", 2015, """Strategically hire and manage your workforce to outcompete rival fast food chains.""", 7.851),
    ("The 7th Continent", 2017, """Journey through a vibrant but deadly land to uncover the key to lifting your curse.""", 7.841),
    ("Agricola", 2007, """Build your farmstead by sowing fields and raising livestock. But don't forget to eat!""", 7.837),
    ("Pandemic Legacy: Season 2", 2017, """The world is a mystery after a devastating pandemic—where will your team go?""", 7.820),
    ("Mansions of Madness: Second Edition", 2016, """Unravel mysteries in Arkham with your investigative team in this app-guided game.""", 7.819),
    ("Blood Rage", 2015, """Ragnarök has come! Secure your place in Valhalla in epic Viking battles.""", 7.819),
    ("Everdell", 2018, """Use resources to build a village of critters and constructions in this woodland game.""", 7.792),
    ("Kingdom Death: Monster", 2015, """Try to survive in a nightmarish world that lies under eternal darkness.""", 7.782),
    ("Power Grid", 2004, """Bid, network, and manage resources in a race to supply the most cities with power.""", 7.759),
    ("Tzolk'in: The Mayan Calendar", 2012, """Lead your people, build monuments and make offerings to earn the favour of the gods.""", 7.758),
    ("Mechs vs. Minions", 2016, """Cooperatively program and pilot your mechs to defeat an army of marauding minions.""", 7.748),
    ("Star Wars: Imperial Assault", 2014, """Play as rebel or imperial forces to fulfil mission objectives.""", 7.743),
    ("Maracaibo", 2019, """Seafarers work to obtain wealth and fame in the 17th century Caribbean.""", 7.743),
    ("Clans of Caledonia", 2017, """Lead your unique Scottish clan to economic might via production, trade, and export.""", 7.735),
    ("Through the Ages: A Story of Civilization", 2006, """Lead your civilization through strategic drafting of leaders, technologies, and more.""", 7.721),
    ("Le Havre", 2008, """Establish a supply chain by collecting resources, building industries, and shipping.""", 7.719),
    ("The Crew: The Quest for Planet Nine", 2019, """Go on a planet-discovering space mission in this cooperative trick-taking game.""", 7.715),
    ("Azul", 2017, """Artfully embellish the walls of your palace by drafting the most beautiful tiles.""", 7.714),
    ("Eclipse", 2011, """Build an interstellar civilization by exploration, research, conquest, and diplomacy.""", 7.712),
    ("Underwater Cities", 2018, """Develop the cities of the sea floor through science, production, and politics.""", 7.710),
    ("Anachrony", 2017, """Use Exosuits & time travel to ensure your vision for the future after the cataclysm.""", 7.701),
    ("Too Many Bones", 2017, """Toss gobs of unique dice in an epic adventure en route to a final boss showdown.""", 7.698),
    ("The Voyages of Marco Polo", 2015, """Using unique abilities, fulfill contracts and reach your goals along the Silk Road.""", 7.679),
    ("Robinson Crusoe: Adventures on the Cursed Island", 2012, """Work together, with Friday, or alone to survive on a desert island.""", 7.677),
    ("Android: Netrunner", 2012, """Megacorporation versus Netrunner in this futuristic cyberpunk game of cat and mouse.""", 7.676),
    ("Marvel Champions: The Card Game", 2019, """Battle Marvel villains with unique teams of iconic heroes in this LCG.""", 7.673),
    ("The Gallerist", 2015, """Amass a fortune, and stake your reputation by operating a lucrative art gallery.""", 7.662),
    ("Race for the Galaxy", 2007, """Worlds await! Colonize, develop and conquer taking advantage of others' choices.""", 7.656),
    ("7 Wonders", 2010, """Draft cards to develop your ancient civilization and build its Wonder of the World.""", 7.654),
    ("Fields of Arle", 2014, """Construct dikes, drain bogs, harvest flax and tend to newborn animals in East Frisia.""", 7.653),
    ("Teotihuacan: City of Gods", 2018, """Use your worker dice to raise the legendary and breathtaking Pyramid of the Sun.""", 7.643),
    ("Clank!: A Deck-Building Adventure", 2016, """Claim your treasures but don't attract the dragon in this deck-building dungeon race.""", 7.636),
    ("Dominant Species", 2010, """With an ice age approaching, which animals will best propagate, migrate, and adapt?""", 7.636),
    ("Five Tribes", 2014, """Move assassins, elders & builders through Naqala to claim oases & control djinns.""", 7.633),
    ("Lords of Waterdeep", 2012, """Deploy agents and hire adventurers to expand your control over the city of Waterdeep.""", 7.625),
    ("Keyflower", 2012, """Compete in a unique auction system to build the most prosperous village.""", 7.623),
    ("Lisboa", 2017, """Compete to reconstruct the city of Lisboa after the great earthquake of 1755.""", 7.617),
    ("Crokinole", 1876, """Flick discs and make trick shots in this traditional Canadian dexterity game!""", 7.617),
    ("Aeon's End", 2016, """Use gems, relics, and spells to channel energy from the breaches against The Nameless""", 7.616),
    ("The Quacks of Quedlinburg", 2018, """Pull ingredients from your stock to make your pot bubble, but hopefully not explode!""", 7.611),
    ("Agricola (Revised Edition)", 2016, """Prosper your farm in an updated and streamlined edition of this acclaimed game.""", 7.610),
    ("Caylus", 2005, """Entrepreneurs pay workers & bribe an official to build a Château & gain royal favor.""", 7.608),
    ("Barrage", 2019, """Nations vie for hydroelectric dominance in a dystopia where water is power.""", 7.605),
    ("On Mars", 2020, """Be a part of the first Martian colony, striving to be the best contributor.""", 7.602),
    ("Clank! Legacy: Acquisitions Incorporated", 2019, """\"Go forth, be bold, and ACQUIRE!\" in this campaign version of \"Clank!\"""", 7.598),
    ("Paladins of the West Kingdom", 2019, """Invaders are coming from everywhere. Keep the faith and defend your homeland.""", 7.592),
    ("El Grande", 1995, """Use your caballeros to control regions of medieval Spain, keeping clear of the King!""", 7.592),
    ("Twilight Imperium: Third Edition", 2005, """Epic empire-building game of interstellar conflict, trade, and struggle for power.""", 7.585),
    ("Architects of the West Kingdom", 2018, """Will you be a virtuous or nefarious servant of the king? Build your way to glory.""", 7.580),
    ("Eldritch Horror", 2013, """An unknown Elder God approaches the world—and you must solve mysteries to stop it.""", 7.579),
    ("Battlestar Galactica: The Board Game", 2008, """How can the human race survive when you don't know who is actually human?""", 7.576),
    ("Rising Sun", 2018, """Lead your clan to victory through negotiation, combat, monsters and favors from Kami.""", 7.574),
    ("Mombasa", 2015, """Acquire shares of unique companies and propagate their trading posts to rake in cash.""", 7.573),
    ("Dominion: Intrigue", 2009, """Enlist torturers, swindlers, and saboteurs to gain wealth and dominate the kingdom.""", 7.573),
    ("Troyes", 2010, """Defend the city and rise to power by influencing the merchants, knights and clergy.""", 7.572),
    ("Tainted Grail: The Fall of Avalon", 2019, """Exploration, battle and diplomacy in a dark Arthurian realm.""", 7.569),
    ("Patchwork", 2014, """Piece together a quilt and leave no holes to become the button master.""", 7.552),
    ("Russian Railroads", 2013, """Acquire locomotives & industry, build track, and hire the best engineers in Russia.""", 7.546),
    ("Raiders of the North Sea", 2015, """Assemble and prepare a formidable crew of vikings to pillage towns and gain glory.""", 7.538),
    ("Codenames", 2015, """Give your team clever one-word clues to help them spot their agents in the field.""", 7.536),
    ("Tigris & Euphrates", 1997, """Keep your Mesopotamian civilisation in perfect balance through revolutions and wars.""", 7.533),
    ("Roll for the Galaxy", 2014, """Utilize your dice populace to develop technologies, settle worlds, and ship goods.""", 7.532),
    ("Pax Pamir (Second Edition)", 2019, """Swing the tides of the "Great Game" as countries vie for control of Afghanistan.""", 7.530),
    ("Grand Austria Hotel", 2015, """Serve guests and prepare rooms to be the best hotelier in the Viennese modern age.""", 7.529),
    ("The Lord of the Rings: Journeys in Middle-Earth", 2019, """Heroes explore Middle-earth, working together to combat evil in an epic campaign.""", 7.528),
    ("Trajan", 2011, """Manage and rule all aspects of Ancient Rome with a clever action selection mancala.""", 7.524),
    ("Sherlock Holmes Consulting Detective: The Thames Murders & Other Cases", 1982, """The game is afoot as you and your irregular friends search Victorian London for clues""", 7.521),
    ("Dominion", 2008, """Acquire the most valuable lands by building your deck with treasure and power cards.""", 7.514),
    ("Pandemic", 2008, """Your team of experts must prevent the world from succumbing to a viral pandemic.""", 7.510),
    ("Lorenzo il Magnifico", 2016, """Avoid excommunication and lead your family to power during the Italian Renaissance.""", 7.506),
    ("Pandemic: Iberia", 2016, """Travel from Barcelona to Lisboa to cure malaria, typhus, yellow fever, and cholera.""" ,7.504)
]

bgs = [{'name': bg[0], 'year': bg[1], 'description': bg[2], 'score': bg[3]} for bg in bgs_raw]
